[build]
  command = "npm run build"
  publish = ".next"
[[plugins]]
  package = "@netlify/plugin-nextjs"
[[redirects]]
  from = "/"
  to = "https://timmybytes.com/blog"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
